-- Run this migration to add extended warehouse fields
ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS address_line1 TEXT;
ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS address_line2 TEXT;
ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS city VARCHAR(100);
ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS state VARCHAR(100);
ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS zip VARCHAR(20);
ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS country VARCHAR(100);
ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS contact_person VARCHAR(200);
ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS email VARCHAR(200);
ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS fax VARCHAR(50);
