ALTER TABLE sales_orders ADD COLUMN IF NOT EXISTS subject          TEXT;
ALTER TABLE sales_orders ADD COLUMN IF NOT EXISTS discount_pct     NUMERIC(5,2)  NOT NULL DEFAULT 0;
ALTER TABLE sales_orders ADD COLUMN IF NOT EXISTS shipping_charges NUMERIC(12,2) NOT NULL DEFAULT 0;
