-- Recurring Invoice's Discount %, Shipping Charges, and Round Off are fully
-- built and calculated into the on-screen Net total, but the columns never
-- existed on recurring_invoices, so none of the three were ever persisted or
-- carried over into the Sales Invoice generated by /execute.
ALTER TABLE recurring_invoices ADD COLUMN IF NOT EXISTS discount_pct NUMERIC(6,2) NOT NULL DEFAULT 0;
ALTER TABLE recurring_invoices ADD COLUMN IF NOT EXISTS shipping_charges NUMERIC(18,2) NOT NULL DEFAULT 0;
ALTER TABLE recurring_invoices ADD COLUMN IF NOT EXISTS round_off NUMERIC(18,2) NOT NULL DEFAULT 0;
